apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: kolide-check-validator
  namespace: naisdevice
  labels:
    app: kolide-check-validator
    team: naisdevice
spec:
  accessPolicy:
    outbound:
      external:
      - host: slack.com
      - host: hooks.slack.com
      - host: k2.kolide.com
  backoffLimit: 0
  completions: 1
  envFrom:
    - secret: kolide-check-validator
  failedJobsHistoryLimit: 1
  image: {{ image }}
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  restartPolicy: Never
  schedule: "*/15 * * * *"
  skipCaBundle: true
  successfulJobsHistoryLimit: 1
  timeZone: Europe/Oslo
---
apiVersion: v1
kind: Secret
metadata:
  name: kolide-check-validator
  namespace: naisdevice
  annotations:
    source: "github.com/nais/kolide-check-validator"
  labels:
    team: naisdevice
stringData:
  KOLIDE_API_TOKEN: "{{ KOLIDE_API_TOKEN }}"
  SLACK_WEBHOOK: "{{ SLACK_WEBHOOK }}"
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    team: naisdevice
  name: kolide-check-validator
  namespace: naisdevice
spec:
  groups:
  - name: kolide-check-validator
    rules:
    - alert: kolide-check-validator has not run for 30 minutes
      annotations:
        action: |
          Check if CronJob -> Job -> pod has run successfully:
          - `kubectl describe cronjob -n naisdevice kolide-check-validator`
          - `kubectl describe pod -n naisdevice -l app=kolide-check-validator`
          - `kubectl logs -n naisdevice -l app=kolide-check-validator -c kolide-check-validator --prefix=true`
      expr: 'time() - max(kube_job_status_completion_time{job_name=~"kolide-check-validator-.+"}) > (60*30)'
      for: 1m
      labels:
        namespace: naisdevice
        severity: warning
