apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kolide-check-validator
  namespace: naisdevice
  labels:
    app: kolide-check-validator
spec:
  schedule: "*/15 * * * *"
  startingDeadlineSeconds: 600
  failedJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10800
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: kolide-check-validator
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 300
          containers:
            - name: kolide-check-validator
              image: {{ image }}
              envFrom:
                - secretRef:
                    name: kolide-check-validator
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "250m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
---
apiVersion: v1
kind: Secret
metadata:
  name: kolide-check-validator
  namespace: naisdevice
  labels:
    source: github.com/nais/kolide-check-validator
stringData:
  KOLIDE_API_TOKEN: "{{ KOLIDE_API_TOKEN }}"
  SLACK_WEBHOOK: "{{ SLACK_WEBHOOK }}"