name: Build and deploy image
on: push
permissions:
  contents: read
jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mise_task:
          - check:deadcode
          - check:gosec
          - check:govet
          - check:govulncheck
          - check:staticcheck
          - ci:fmt
          - test
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6.0.3
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # ratchet:jdx/mise-action@v4
      - run: mise run ${{ matrix.mise_task }}

  build_and_push:
    if: github.ref == 'refs/heads/main'
    name: Build and push application image to GAR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6.0.3
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # ratchet:jdx/mise-action@v4
      - id: go-version
        run: echo "version=$(mise current go)" >> $GITHUB_OUTPUT
      - uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: nais
          build_args: GO_VERSION=${{ steps.go-version.outputs.version }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - uses: nais/deploy/actions/deploy@c55d6073d913975d2dada508bdfefc6427d39867 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
