name: CI/CD
on: push

env:
  IMAGE_WITHOUT_TAG: ghcr.io/${{ github.repository }}

jobs:
  get-image-tag:
    name: Get Docker image tag
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.get-image-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Output Docker image tag
        id: get-image-tag
        run: echo ::set-output name=tag::$(date "+%Y-%m-%d")-$(git rev-parse --short HEAD)

  test-build-and-push:
    name: Test, build and push the Docker image to GHCR
    needs: get-image-tag
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, test and push the Docker image
        run: |
          IMAGE=${IMAGE_WITHOUT_TAG}:${{ needs.get-image-tag.outputs.tag }}
          docker build --pull --tag ${IMAGE} .
          docker push ${IMAGE}

  deployToProd:
    name: Deploy to production
    needs:
      - get-image-tag
      - test-build-and-push
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAISDEVICE_DEPLOY_APIKEY }}
          IMAGE: ${IMAGE_WITHOUT_TAG}:${{ needs.get-image-tag.outputs.tag }}
          CLUSTER: prod-gcp
          RESOURCE: ".nais/nais.yml"
          VAR: "\
              KOLIDE_API_TOKEN=${{ secrets.KOLIDE_API_TOKEN }},\
              SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}"