name: CI/CD
on: push

jobs:
  build_and_push:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: naisdevice
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_
          identity_provider: ${{ secrets.NAIS_WORKLOAD_
      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAISDEVICE_DEPLOY_APIKEY }}
          IMAGE: ${{ steps.docker-push.outputs.image }}
          CLUSTER: prod-gcp
          RESOURCE: ".nais/nais.yml"
          VAR: "\
              KOLIDE_API_TOKEN=${{ secrets.KOLIDE_API_TOKEN }},\
              SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}"
