name: "kolide-check-validator CI/CD"
on: push

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  test-build-and-push:
    name: Test, build and push the Docker image to GHCR
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, test and push the Docker image
        run: |
          docker build --pull --tag ${IMAGE} .
          docker push ${IMAGE}