name: Build and deploy image
on: push
permissions:
  contents: read
jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mise_task:
          - check:deadcode
          - check:gosec
          - check:govet
          - check:govulncheck
          - check:staticcheck
          - ci:fmt
          - test
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # ratchet:jdx/mise-action@v3
      - run: mise run ${{ matrix.mise_task }}

  build_and_push:
    if: github.ref == 'refs/heads/main'
    name: Build and push application image to GAR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # ratchet:jdx/mise-action@v3
      - id: go-version
        run: echo "version=$(mise current go)" >> $GITHUB_OUTPUT
      - uses: nais/docker-build-push@ae613eff6f44f0323476eda1c3994a7c518761c3 # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: nais
          build_args: GO_VERSION=${{ steps.go-version.outputs.version }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
