name: Build and deploy image
on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - run: make test
      - run: make check
      - id: go-version
        run: echo "version=$(mise current go)" >> $GITHUB_OUTPUT
      - run: |
          make fmt
          git diff --exit-code --name-only

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: naisdevice
          build_args: GO_VERSION=${{ steps.go-version.outputs.version }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yml
          IMAGE: ${{ steps.docker-push.outputs.image }}
